[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"

[tool.pylint."MESSAGES CONTROL"]
disable = [ "invalid-name, missing-module-docstring, missing-class-docstring, missing-function-docstring, import-error"]
